### ISSUE TITLE
👀 Actualizar las dependencias del package.json a unas mas recientes

### ISSUE THREAD

**Issue by rickytodev** [SofiDevO/portfolio-sofi2.0#23]
### Lo de amarillo son los paquetes que podemos actualizar y otra cosa que podríamos hacer es usar versiones exactas quitando `^` para que quede una versión en concreto.

![{4B6F2029-329A-4596-B93F-40E479FF4B81}](https://github.com/user-attachments/assets/0aeeb134-53c0-4f36-8021-d981fe06bbad)

**Comment by SofiDevO** [comment]
Se tiene que probar compatibilidad y estabilidad antes de hacer cualquier upgrade
